export const IS_FETCHING = 'IS_FETCHING';
export const USER_RECEIVED = 'USER_RECEIVED';
export const MODAL_OPENED = 'MODAL_OPENED';
export const MODAL_CLOSED = 'MODAL_CLOSED';
export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
export const ADMIN_STATUS_CHANGED = 'ADMIN_STATUS_CHANGED';
export const CHANGE_LOGIN = 'CHANGE_LOGIN';
export const CREATE_USER_FETCHING = 'CREATE_USER_FETCHING';
export const USER_IS_NOT_CREATED = 'USER_IS_NOT_CREATED';
export const USER_CREATED = 'USER_CREATED';
export const USER_LOGIN_CHANGED = 'USER_LOGIN_CHANGED';
export const USER_FIRST_NAME_CHANGED = 'USER_FIRST_NAME_CHANGED';
export const USER_LAST_NAME_CHANGED = 'USER_LAST_NAME_CHANGED';
export const USER_ADMIN_STATUS_CHANGED = 'USER_ADMIN_STATUS_CHANGED';
export const USER_FORM_FIELDS_SET = 'USER_FORM_FIELDS_SET';
export const DEVICE_FORM_FIELDS_SET = 'DEVICE_FORM_FIELDS_SET';
export const CURRENT_USER_RECEIVED = 'CURRENT_USER_RECEIVED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const USER_NOT_RECEIVED = 'USER_NOT_RECEIVED';
export const CHANGE_LOGIN_WHEN_CREATE = 'CHANGE_LOGIN_WHEN_CREATE';
export const CHANGE_PASSWORD_WHEN_CREATE = 'CHANGE_PASSWORD_WHEN_CREATE';
export const LOGOUT = 'LOGOUT';
export const DEFINE_USER = 'DEFINE_USER';



export const DEVICE_MODAL_OPENED = 'DEVICE_MODAL_OPENED';
export const DEVICE_MODAL_CLOSED = 'DEVICE_MODAL_CLOSED';
export const DEVICE_NAME_CHANGED_C = 'DEVICE_NAME_CHANGED_C';
export const DEVICE_TYPES_RECEIVED = 'DEVICE_TYPES_RECEIVED';
export const DEVICE_TYPE_CHANGED = 'DEVICE_TYPE_CHANGED';
export const RESET_FAIL = 'RESET_FAIL';
export const DEVICES_RECEIVED = 'DEVICES_RECEIVED';
export const CURRENT_DEVICE_ERROR = 'CURRENT_DEVICE_ERROR';
export const RESET_DEVICE_FAIL = 'RECET_DEVICE_FAIL';
export const USERS_RECEIVED = 'USERS_RECEIVED';
export const CONTROLS_RECEIVED = 'CONTROLS_RECEIVED';
export const CONFIRM_MODAL_OPEN = 'CONFIRM_MODAL_OPEN';
export const CONFIRM_MODAL_CLOSE = 'CONFIRM_MODAL_CLOSE';


export const CONTROL_MODAL_OPENED = 'CONTROL_MODAL_OPENED';
export const CONTROL_MODAL_CLOSED = 'CONTROL_MODAL_CLOSED';
export const CONTROL_TYPE_CHANGED = 'CONTROL_TYPE_CHANGED';
export const CONTROL_IS_NOT_CREATED = 'CONTROL_IS_NOT_CREATED';
export const CONTROL_NAME_CHANGED_C = 'CONTROL_NAME_CHANGED_C';
export const CONTROL_TYPES_RECEIVED = 'CONTROL_TYPES_RECEIVED';
export const CONTROL_DELETED = 'CONTROL_DELETED';
export const CURRENT_CONTROL_RECEIVED = 'CURRENT_CONTROL_RECEIVED';
export const CONTROL_FORM_FIELDS_SET = 'CONTROL_FORM_FIELDS_SET';
export const CONTROL_CONFIRM_MODAL_OPEN = 'CONTROL_CONFIRM_MODAL_OPEN';
export const CONTROL_CONFIRM_MODAL_CLOSE = 'CONTROL_CONFIRM_MODAL_CLOSE';
export const CONTROL_UUID_CHANGED = 'CONTROL_UUID_CHANGED';
export const CONTROL_NAME_CHANGED = 'CONTROL_NAME_CHANGED';
export const RESET_CONTROL_FAIL = 'RESET_CONTROL_FAIL';
export const CURRENT_CONTROL_ERROR = 'CURRENT_CONTROL_ERROR';


export const DEVICE_IS_NOT_CREATED = 'DEVICE_IS_NOT_CREATED';
export const DEVICE_CONFIRM_MODAL_OPEN = 'DEVICE_CONFIRM_MODAL_OPEN';
export const DEVICE_CONFIRM_MODAL_CLOSE = 'DEVICE_CONFIRM_MODAL_CLOSE';
export const DEVICE_NAME_CHANGED = 'DEVICE_NAME_CHANGED';
export const DEVICE_UUID_CHANGED = 'DEVICE_UUID_CHANGED';

export const PAGES_RECEIVED = 'PAGES_RECEIVED';
export const PAGE_FORM_FIELDS_SET = 'PAGE_FORM_FIELDS_SET';
export const PAGE_FORM_IS_FETCHING = 'PAGE_FORM_IS_FETCHING';
export const PAGE_CONTROL_FORM_ADDED = 'PAGE_CONTROL_FORM_ADDED';
export const CURRENT_PAGE_CONTROL_DELETED = 'CURRENT_PAGE_CONTROL_DELETED';
export const CURRENT_PAGE_RECEIVED = 'CURRENT_PAGE_RECEIVED';
export const CURRENT_PAGE_CONTROL_POSITION_Y_EDITED = 'CURRENT_PAGE_CONTROL_POSITION_Y_EDITED';
export const CURRENT_PAGE_CONTROL_POSITION_X_EDITED = 'CURRENT_PAGE_CONTROL_POSITION_X_EDITED';
export const CURRENT_PAGE_CONTROL_HEIGHT_EDITED = 'CURRENT_PAGE_CONTROL_HEIGHT_EDITED';
export const CURRENT_PAGE_CONTROL_WEIGHT_EDITED = 'CURRENT_PAGE_CONTROL_WEIGHT_EDITED';

export const CURRENT_PAGE_ERROR= 'CURRENT_PAGE_ERROR';
export const RESET_PAGE_FAIL = 'RESET_PAGE_FAIL';
export const PAGE_DELETED = 'PAGE_DELETED';
export const PAGE_CONTROLS_RECEIVED = 'PAGE_CONTROLS_RECEIVED';

export const PAGE_CONFIRM_MODAL_CLOSE = 'PAGE_CONFIRM_MODAL_CLOSE';
export const PAGE_CONFIRM_MODAL_OPEN = 'PAGE_CONFIRM_MODAL_OPEN';
export const PAGE_NAME_EDITED = 'PAGE_NAME_EDITED';
export const PAGE_CAPTION_EDITED = 'PAGE_CAPTION_EDITED';
export const PAGE_WIDTH_EDITED = 'PAGE_WIDTH_EDITED';
export const PAGE_HEIGHT_EDITED = 'PAGE_HEIGHT_EDITED';
export const PAGE_CONTROLS_IS_FETCHING = 'PAGE_CONTROLS_IS_FETCHING';
export const ICONS_IS_FETCHING = 'ICONS_IS_FETCHING';
export const CURRENT_PAGE_IS_FETCHING = 'CURRENT_PAGE_IS_FETCHING';
export const CONTROLS_IS_FETCHING = 'CONTROLS_IS_FETCHING';
export const PAGE_X_POSITION_EDITED = 'PAGE_X_POSITION_EDITED';
export const PAGE_Y_POSITION_EDITED = 'PAGE_Y_POSITION_EDITED';
export const PAGE_ICON_EDITED = 'PAGE_ICON_EDITED';
export const ICONS_RECEIVED = 'ICONS_RECEIVED';
export const PAGE_MODAL_OPENED = 'PAGE_MODAL_OPENED';
export const PAGE_MODAL_CLOSED = 'PAGE_MODAL_CLOSED';
export const ICON_ID_CHANGED = 'ICON_ID_CHANGED';
export const PAGE_NAME_CHANGED = 'PAGE_NAME_CHANGED';
export const PAGE_CONTROL_ADDED = 'PAGE_CONTROL_ADDED';
export const PAGE_CAPTION_CHANGED = 'PAGE_CAPTION_CHANGED';
export const PAGE_WIDTH_CHANGED = 'PAGE_WIDTH_CHANGED';
export const PAGE_HEIGHT_CHANGED = 'PAGE_HEIGHT_CHANGED';
export const PAGE_X_POSITION_CHANGED = 'PAGE_X_POSITION_CHANGED';
export const PAGE_Y_POSITION_CHANGED = 'PAGE_Y_POSITION_CHANGED';
export const PAGE_CREATED = 'PAGE_CREATED';
export const CURRENT_PAGE_CONTROL_SELECTED ='CURRENT_PAGE_CONTROL_SELECTED';







export const CURRENT_USER_ERROR = 'CURRENT_USER_ERROR';
export const USER_DELETED = 'USER_DELETED';
export const DEVICE_DELETED = 'DEVICE_DELETED';
export const CURRENT_DEVICE_RECEIVED = 'CURRENT_DEVICE_RECEIVED';
export const USERS_ERROR = 'USERS_ERROR';
export const RESET_USERS_FAIL = 'RESET_USERS_FAIL';